branch: master
evaluateStr: item => item.linesChanged
collectInterval: 60
onlyRegistered: false
collectMessages: true
repositories:
  - branch: master
    exclude: []
    name: git-log-calendar-teams
    url: https://github.com/makamekm/git-log-calendar-teams.git
  - branch: develop
    exclude:
      - cicd
    name: figma-react
    url: https://github.com/makamekm/figma-react.git
  - branch: master
    exclude: []
    name: react
    url: https://github.com/facebook/react.git
users:
  - associations:
      - hgjghjghj
    name: jhjhjjhj
  - associations:
      - test
    name: mmm
  - associations:
      - makame
      - makame@mail.ru
      - Maxim Karpov
      - Karpov Maxim
    name: Maxim Karpov
  - associations:
      - dan.abramov@gmail.com
    name: Dan Abramov
  - associations:
      - dominic gannaway
    name: Dominic Gannaway
  - associations:
      - andrew clark
    name: Andrew Clark
  - associations:
      - sebastian markbåge
    name: Sebastian Markbåge
  - associations:
      - bvaughn@fb.com
      - brian vaughn
    name: Brian Vaughn
  - associations:
      - threepointone@fb.com
      - sunil pai
    name: Sunil Pai
  - associations:
      - necolas@fb.com
      - nicolas gallagher
    name: Nicolas Gallagher
  - associations:
      - willygdouglas@gmail.com
      - will douglas
    name: Will Douglas
teams:
  - invert: false
    name: Client Onboarding
    users:
      - mmm
      - jhjhjjhj
  - name: team
    users:
      - Dan Abramov
      - Maxim Karpov
  - invert: true
    name: others
    users:
      - mmm
      - jhjhjjhj
      - Dan Abramov
      - Maxim Karpov
