branch: master
cleanTmp: false
debug: true
tmpDir: ./repositories
statsDir: ./
evaluate: item => item.linesChanged
repositories:
  - branch: master
    exclude: []
    name: git-log-calendar-teams
    url: https://github.com/makamekm/git-log-calendar-teams.git
  - branch: develop
    exclude:
      - cicd
    name: figma-react
    url: https://github.com/makamekm/figma-react.git
  - branch: master
    exclude: []
    name: react
    url: https://github.com/facebook/react.git
users:
  - name: jhjhjjhj
    associations:
      - hgjghjghj
  - associations:
      - test
    name: mmm
  - associations:
      - makame
      - makame@mail.ru
      - Maxim Karpov
      - Karpov Maxim
    name: Maxim Karpov
  - associations:
      - dan.abramov@gmail.com
    name: Dan Abramov
  - associations:
      - dominic gannaway
    name: Dominic Gannaway
  - associations:
      - andrew clark
    name: Andrew Clark
  - associations:
      - sebastian markbåge
    name: Sebastian Markbåge
  - associations:
      - bvaughn@fb.com
      - brian vaughn
    name: Brian Vaughn
  - associations:
      - threepointone@fb.com
      - sunil pai
    name: Sunil Pai
  - associations:
      - necolas@fb.com
      - nicolas gallagher
    name: Nicolas Gallagher
  - associations:
      - willygdouglas@gmail.com
      - will douglas
    name: Will Douglas
teams:
  - invert: false
    name: Client Onboarding
    users:
      - mmm
      - jhjhjjhj
  - name: team
    users:
      - Dan Abramov
      - Maxim Karpov
  - invert: true
    name: others
    users:
      - mmm
      - Dan Abramov
      - Maxim Karpov
reportCalendarTeam:
  - team: team
    output: ./team.svg
    compareTeams:
      - others
    limit: 180
  - team: others
    output: ./others.svg
    compareTeams:
      - team
reportCalendarUser:
  - user: Maxim Karpov
    limit: 60
    output: ./mkarpov.svg
  - user: Maxim Karpov
    repositories:
      - git-log-calendar-teams
    compareTeams:
      - team
    output: ./mkarpov-git-log.svg
reportDonutUser:
  - users:
      - Maxim Karpov
    others: true
    output: ./mkarpov-total.svg
  - users:
      - Dan Abramov
    others: true
    repositories:
      - react
    output: ./danabramov-react-total.svg
  - limit: 365
    top: 5
    repositories:
      - react
    output: ./react-year.svg
reportMapUser:
  output: ./connections.svg
reportRunningRepository:
  - limit: 30
    output: ./repositories.svg
  - limit: 365
    output: ./year-repositories.svg
path: /Users/mkarpov/projects/git-log-ui/git-log-config.yml
collectInterval: 15
